// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbZd79PWY3ytGSMp90a1NuN-6dn0pycS0',
    appId: '1:1065417358787:web:cef2c4fa1a29950b3b9176',
    messagingSenderId: '1065417358787',
    projectId: 'ecomerce-e9d8c',
    authDomain: 'ecomerce-e9d8c.firebaseapp.com',
    storageBucket: 'ecomerce-e9d8c.appspot.com',
    measurementId: 'G-GJ8WF7TS9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsecTOrQBRMAmkap8FeNPhiRW8dn9KpN8',
    appId: '1:1065417358787:android:5830bd464b861f343b9176',
    messagingSenderId: '1065417358787',
    projectId: 'ecomerce-e9d8c',
    storageBucket: 'ecomerce-e9d8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO8q9hsB8AThsd6_0YvxVd1iIVmd0W5xo',
    appId: '1:1065417358787:ios:7d84e690242911263b9176',
    messagingSenderId: '1065417358787',
    projectId: 'ecomerce-e9d8c',
    storageBucket: 'ecomerce-e9d8c.appspot.com',
    iosBundleId: 'com.example.ecomerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO8q9hsB8AThsd6_0YvxVd1iIVmd0W5xo',
    appId: '1:1065417358787:ios:7d84e690242911263b9176',
    messagingSenderId: '1065417358787',
    projectId: 'ecomerce-e9d8c',
    storageBucket: 'ecomerce-e9d8c.appspot.com',
    iosBundleId: 'com.example.ecomerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbZd79PWY3ytGSMp90a1NuN-6dn0pycS0',
    appId: '1:1065417358787:web:f41bdd8fbb640e253b9176',
    messagingSenderId: '1065417358787',
    projectId: 'ecomerce-e9d8c',
    authDomain: 'ecomerce-e9d8c.firebaseapp.com',
    storageBucket: 'ecomerce-e9d8c.appspot.com',
    measurementId: 'G-F9Y0LHWHPL',
  );
}
